[package]
name = "nfa"
version = "0.1.0"
authors = ["Bever1337 <bever1337@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
regex-syntax = "0.6.25"